# Title: Assigment 1 of CS512- Computer Vision
## Term: Fall 2018
## Author: Diego Martin Crespo
## Id: A20432558

In [1]:
# Necesary libraries for operations
import numpy as np
from random import randint, uniform,random
import math

## 1. QUESTION:

In [2]:
# 1.a:
print('1.a \n')
d=1
p=np.matrix([[3],[2],[1]])
f=np.matrix([[10,0,0],[0,10,0],[0,0,10]])
projection=d*np.dot(f,p)
print('The projected vector (3,2,1) onto an image is: \n', projection.transpose(), '\n \n')

### 1.b: 
print('1.b \n')
print('The pinhole camera model where the image is behind the cemter of projection corresponds better to physical pinhole camera model because in a camera the image is produced behind the center of projection. The equation is the same for both models but with the adition of a minus sign. \n \n')

### 1.c: 
print('1.c \n')
print('-> When the focal length gets bigger the projection of the image gets bigger.')
print('-> When the distance to the obeject gets bigger the projection gets smaller. \n \n')

### 1.d:
print('1.d \n')
p2d=np.array([1,1])
print('For example, knowing that the 2D vector (U,V)=(1,1), the 2DH vector is defined as (u,v,w) where U=u/w & V=v/w. Therefore for instance: (1,1,1) or (2,2,2) 2DH vectors will correspond to (1,1) 2D vector. \n \n')

### 1.e:
print('1.e \n')
p2dH=np.array([1,1,2])
u=p2dH[0]/p2dH[2]
v=p2dH[1]/p2dH[2]
print('The 2D point of (1,1,2) is: (',u,',',v,'). \n \n')

### 1.f: 
print('1.f \n')
print('It represents a vector (A point in the infinite). \n \n')

### 1.g: 
print('1.g \n')
print('Homogenious coordinates able you to work linearly. You simply postone the conversion to basic coordenates at the last moment (when you divide by z). \n \n')

### 1.h: 
print('1.h \n')
print('M is 3x4')
print('k is 3x3')
print('I is 3x3')
print('0 is 3x1')
print('\n \n')

### 1.i: 
print('1.i \n')
M=np.matrix([[1,2,3,4],[5,6,7,8],[1,2,1,2]])
p3d=np.matrix([[1],[2],[3],[1]])
p2dH=np.dot(M,p3d)
u=p2dH[0,0]/p2dH[2,0]
v=p2dH[1,0]/p2dH[2,0]
p2d=np.matrix([[u],[v]])
print('The projection of P using M i de 2D point, p: \n',p2d.transpose(),' \n \n')

1.a 

The projected vector (3,2,1) onto an image is: 
 [[30 20 10]] 
 

1.b 

The pinhole camera model where the image is behind the cemter of projection corresponds better to physical pinhole camera model because in a camera the image is produced behind the center of projection. The equation is the same for both models but with the adition of a minus sign. 
 

1.c 

-> When the focal length gets bigger the projection of the image gets bigger.
-> When the distance to the obeject gets bigger the projection gets smaller. 
 

1.d 

For example, knowing that the 2D vector (U,V)=(1,1), the 2DH vector is defined as (u,v,w) where U=u/w & V=v/w. Therefore for instance: (1,1,1) or (2,2,2) 2DH vectors will correspond to (1,1) 2D vector. 
 

1.e 

The 2D point of (1,1,2) is: ( 0.5 , 0.5 ). 
 

1.f 

It represents a vector (A point in the infinite). 
 

1.g 

Homogenious coordinates able you to work linearly. You simply postone the conversion to basic coordenates at the last moment (when you divid

## 2. QUESTION:

In [3]:
### 2.a:
print('2.a \n')
p=np.matrix([[1],[1],[1]])
pt=np.array([2,3])
f=np.matrix([[1,0,pt[0]],[0,1,pt[1]],[0,0,1]])
ptrans=d*np.dot(f,p)
print('The translated point given the point (1,1) and translating it with the point (2,3) is: \n', ptrans[[0,1],:].transpose(), '\n \n')

### 2.b:
print('2.b \n')
ps=np.array([2,2])
f2b=np.matrix([[ps[0],0,0],[0,ps[1],0],[0,0,1]])
ptrans=d*np.dot(f2b,p)
print('The scaled point given the point (1,1) and translating it with the point (2,3) is: \n', ptrans[[0,1],:].transpose() , '\n \n')

### 2.c:
print('2.c \n')
f2c=np.matrix([[math.cos(45*math.pi/180),-math.sin(45*math.pi/180),0],[math.sin(45*math.pi/180),math.cos(45*math.pi/180),0],[0,0,1]])
ptrans=d*np.dot(f2c,p)
print('The rotated point of 45º given the point (1,1) is: \n', ptrans[[0,1],:].transpose().round(3) , '\n \n')

### 2.d:
print('2.d \n')
f=np.matrix([[1,0,ps[0]],[0,1,ps[1]],[0,0,1]])
ft=np.matrix([[1,0,-ps[0]],[0,1,-ps[1]],[0,0,1]])
paux=d*np.dot(f,f2c)
paux2=np.dot(paux,ft)
ffinal=np.dot(paux2,p)
print('The rotated point of 45º arround the point (2,2) given the point (1,1) is: \n', ffinal[[0,1],:].transpose().round(3) , '\n \n')

### 2.e:
print('2.e \n')
print('The convined matrix should be: TRP \n \n')

### 2.f:
print('2.f \n')
print('The effect is a scale by (3,2) \n \n')

### 2.g:
print('2.g \n')
print('The effect is a translation by (1,2) \n \n')

### 2.h:
print('2.h \n')
f=np.matrix([[1/3,0,0],[0,1/2,0],[0,0,1]])
print('The transformation matrix that will reverse the given transformation is:',f.round(2),' \n \n')

### 2.i:
print('2.i \n')
print('The inverse of M=R(45)T(1,2) will be T^(-1)=(R(45)T(1,2))^(-1)= T(1,2)^(-1)R(45)^(-1)= T(-1,-2)R(-45). \n \n')

### 2.j:
print('2.j \n')
print('A perpendicular vecor (u,v) to (1,3) will satisfy the equation (1,3)(u,v)=0. For instance: (3,-1). \n \n')

### 2.k:
print('2.k \n')
u=np.array([1,3])
v=np.array([2,5])
vnorm=np.linalg.norm(v)
proj=np.dot(u,v)/(math.pow(vnorm,2))*v
print('The projection of the vector (1,3) onto the direction defined by the vector (2,5) is:',proj.round(3),' \n \n')

2.a 

The translated point given the point (1,1) and translating it with the point (2,3) is: 
 [[3 4]] 
 

2.b 

The scaled point given the point (1,1) and translating it with the point (2,3) is: 
 [[2 2]] 
 

2.c 

The rotated point of 45º given the point (1,1) is: 
 [[0.    1.414]] 
 

2.d 

The rotated point of 45º arround the point (2,2) given the point (1,1) is: 
 [[2.    0.586]] 
 

2.e 

The convined matrix should be: TRP 
 

2.f 

The effect is a scale by (3,2) 
 

2.g 

The effect is a translation by (1,2) 
 

2.h 

The transformation matrix that will reverse the given transformation is: [[0.33 0.   0.  ]
 [0.   0.5  0.  ]
 [0.   0.   1.  ]]  
 

2.i 

The inverse of M=R(45)T(1,2) will be T^(-1)=(R(45)T(1,2))^(-1)= T(1,2)^(-1)R(45)^(-1)= T(-1,-2)R(-45). 
 

2.j 

A perpendicular vecor (u,v) to (1,3) will satisfy the equation (1,3)(u,v)=0. For instance: (3,-1). 
 

2.k 

The projection of the vector (1,3) onto the direction defined by the vector (2,5) is: [1.172 2.931]  
 



## 3. QUESTION:

In [4]:
### 3.a:
print('3.a \n')
print('For not need to know where the camera is to refer in the world. \n \n')

### 3.b:
print('3.b \n')
print('The transformation matrix will be p(c)=R^(-1)T^(-1)p(w) \n \n')

### 3.c:
print('3.c \n')
f3c=np.matrix([["x1","y1","z1"],["x2","y2","z2"],["x3","y3","z3"]])
print('Being x,y,z unit vectors, the rThank otation matrix will be: \n',f3c,' \n \n')

### 3.d:
print('3.d \n')
print('R* is the rotation matrix from world to camera R*=R^(T) \n')
print('T* is the translation matrix from world to camera T*=(-R)^(T)T \n \n')

### 3.e:
print('3.e \n')
f3e=np.matrix([["ku","0","512"],["0","kv","512"],["0","0","1"]])
print('Given ku pixels per mm in the x direction, kv pixels per mm in the y direction, and the optical center of the camera is translated by (512,512) pixels, the transformation matrix will be: \n',f3e,' \n \n')

### 3.f:
print('3.f \n')
print('k* contains the instrinsic parameters:\n')
print('-> focal length [mm] \n')
print('-> scale [pixel/mm] \n')
print('-> translation of optical center [mm] \n')
print('R* and T* contains the extrensic parameters: rotation and translation of world with respect to camera.')
print(' \n \n')

### 3.g:
print('3.g \n')
print('It is used to adjust the desviation angle introduced when the camera captures the image. It is a small desviation, but it is better to work with higher precision. \n \n')

### 3.h:
print('3.h \n')
print('It introduces a new scale to the model.\n')
print('The dificulty is that it is not linear.')
print('\n \n')

### 3.i:
print('3.i \n')
print('A weak prespective camera makes all lines parallel, there is no vanishing point. It is a good approximation when depth variation is small compared to distance from object. \n \n')

3.a 

For not need to know where the camera is to refer in the world. 
 

3.b 

The transformation matrix will be p(c)=R^(-1)T^(-1)p(w) 
 

3.c 

Being x,y,z unit vectors, the rThank otation matrix will be: 
 [['x1' 'y1' 'z1']
 ['x2' 'y2' 'z2']
 ['x3' 'y3' 'z3']]  
 

3.d 

R* is the rotation matrix from world to camera R*=R^(T) 

T* is the translation matrix from world to camera T*=(-R)^(T)T 
 

3.e 

Given ku pixels per mm in the x direction, kv pixels per mm in the y direction, and the optical center of the camera is translated by (512,512) pixels, the transformation matrix will be: 
 [['ku' '0' '512']
 ['0' 'kv' '512']
 ['0' '0' '1']]  
 

3.f 

k* contains the instrinsic parameters:

-> focal length [mm] 

-> scale [pixel/mm] 

-> translation of optical center [mm] 

R* and T* contains the extrensic parameters: rotation and translation of world with respect to camera.
 
 

3.g 

It is used to adjust the desviation angle introduced when the camera captures the image. It is a small 

## 4. QUESTION:

In [5]:
### 4.a:
print('4.a \n')
print('Surface variance: power of light per surface area reflected from surface. \n')
print('Image Irradiance: power of light per surface area received at each pixel')
print('\n \n')

### 4.b:
print('4.b \n')
print('E(p)=L(p)(pi/4)(d/f)cos4(alfa) \n \n')

### 4.c:
print('4.c \n')
print('The albedo is the ratio of irradiance reflected to the irradiacne received by a surface. \n \n')

### 4.d:
print('4.d \n')
print('The choice of primary colors is related to how the human eye works. \n \n')

### 4.e:
print('4.e \n')
print('It is the grey scale \n \n')

### 4.f:
print('4.f \n')
print('The RGB scale was created by comparing the real colours to the resulting mix of the RGB values. It was done empirically. \n \n')

### 4.g:
print('4.g \n')
print('It contains the black (1) and white (0) information of a pixel. \n \n')

### 4.h:
print('4.h \n')
print('Its advantage is that in LAB color space euclidean distance is representative of the perception of distance. That is not true RGB.\n \n')

4.a 

Surface variance: power of light per surface area reflected from surface. 

Image Irradiance: power of light per surface area received at each pixel

 

4.b 

E(p)=L(p)(pi/4)(d/f)cos4(alfa) 
 

4.c 

The albedo is the ratio of irradiance reflected to the irradiacne received by a surface. 
 

4.d 

The choice of primary colors is related to how the human eye works. 
 

4.e 

It is the grey scale 
 

4.f 

The RGB scale was created by comparing the real colours to the resulting mix of the RGB values. It was done empirically. 
 

4.g 

It contains the black (1) and white (0) information of a pixel. 
 

4.h 

Its advantage is that in LAB color space euclidean distance is representative of the perception of distance. That is not true RGB.
 

